rootUrl: http://localhost:8080/components/vaadin-grid/test/visual/
gridUrl: http://localhost:4444/wd/hub
screenshotsDir: ./test/visual/screens

system:
  plugins:
    polyserve:
      port: 8080
    sauce: true

browsers:
  chrome:
    desiredCapabilities:
      browserName: "chrome"
      version: "66.0"
      platform: "Windows 10"

  # Selenium with Firefox receives the following error in "sorting" tests:
  # "Permission denied to access property "__eventWrappers1527612800414""
  #
  # firefox:
  #   desiredCapabilities:
  #     browserName: "firefox"
  #     version: "47.0"
  #     platform: "Windows 10"

  # The following setups don't currently work due to Selenium SafariDriver issue
  # https://github.com/vaadin/vaadin-element-skeleton/issues/19
  #
  # safari:
  #   desiredCapabilities:
  #     browserName: "safari"
  #     version: "10.0"
  #     platform: "OS X 10.11"
  #
  # iphone:
  #   desiredCapabilities:
  #     browserName: "iphone"
  #     version: "9.2"
  #     platform: "OS X 10.11"
  #
  # ipad:
  #   desiredCapabilities:
  #     browserName: "ipad"
  #     version: "9.2"
  #     platform: "OS X 10.11"
